export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

export const CHANGE_USER_STATE_REQUEST = 'CHANGE_USER_STATE_REQUEST'
export const CHANGE_USER_STATE_SUCCESS = 'CHANGE_USER_STATE_SUCCESS'
export const CHANGE_USER_STATE_ERROR = 'CHANGE_USER_STATE_ERROR'

export const ADD_AGENT_REQUEST = 'ADD_AGENT_REQUEST'
export const ADD_AGENT_SUCCESS = 'ADD_AGENT_SUCCESS'
export const ADD_AGENT_ERROR = 'ADD_AGENT_ERROR'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'