export const FETCH_RESERVATIONS_REQUEST = 'FETCH_RESERVATIONS_REQUEST'
export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS'
export const FETCH_RESERVATIONS_ERROR = 'FETCH_RESERVATIONS_ERROR'

export const CONFIRM_RESERVATION_REQUEST = 'CONFIRM_RESERVATION_REQUEST'
export const CONFIRM_RESERVATION_SUCCESS = 'CONFIRM_RESERVATION_SUCCESS'
export const CONFIRM_RESERVATION_ERROR = 'CONFIRM_RESERVATION_ERROR'

export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST'
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS'
export const CREATE_RESERVATION_ERROR = 'CREATE_RESERVATION_ERROR'

export const DELETE_RESERVATION_REQUEST = 'DELETE_RESERVATION_REQUEST'
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS'
export const DELETE_RESERVATION_ERROR = 'DELETE_RESERVATION_ERROR'

export const RESET_RESERVATIONS = 'RESET_RESERVATIONS'