//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.09 at 10:55:37 AM CET 
//


package com.megatravel.agent.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.agent.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.agent.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateApartmentRequest }
     * 
     */
    public CreateApartmentRequest createCreateApartmentRequest() {
        return new CreateApartmentRequest();
    }

    /**
     * Create an instance of {@link ApartmentDTO }
     * 
     */
    public ApartmentDTO createApartmentDTO() {
        return new ApartmentDTO();
    }

    /**
     * Create an instance of {@link CreateApartmentResponse }
     * 
     */
    public CreateApartmentResponse createCreateApartmentResponse() {
        return new CreateApartmentResponse();
    }

    /**
     * Create an instance of {@link CreateReservationRequest }
     * 
     */
    public CreateReservationRequest createCreateReservationRequest() {
        return new CreateReservationRequest();
    }

    /**
     * Create an instance of {@link ReservationDTO }
     * 
     */
    public ReservationDTO createReservationDTO() {
        return new ReservationDTO();
    }

    /**
     * Create an instance of {@link CreateReservationResponse }
     * 
     */
    public CreateReservationResponse createCreateReservationResponse() {
        return new CreateReservationResponse();
    }

    /**
     * Create an instance of {@link ConfirmReservationRequest }
     * 
     */
    public ConfirmReservationRequest createConfirmReservationRequest() {
        return new ConfirmReservationRequest();
    }

    /**
     * Create an instance of {@link ConfirmReservationResponse }
     * 
     */
    public ConfirmReservationResponse createConfirmReservationResponse() {
        return new ConfirmReservationResponse();
    }

    /**
     * Create an instance of {@link ApartmentTypeDTO }
     * 
     */
    public ApartmentTypeDTO createApartmentTypeDTO() {
        return new ApartmentTypeDTO();
    }

    /**
     * Create an instance of {@link ApartmentCategoryDTO }
     * 
     */
    public ApartmentCategoryDTO createApartmentCategoryDTO() {
        return new ApartmentCategoryDTO();
    }

    /**
     * Create an instance of {@link AgentLoginRequest }
     * 
     */
    public AgentLoginRequest createAgentLoginRequest() {
        return new AgentLoginRequest();
    }

    /**
     * Create an instance of {@link AgentLoginResponse }
     * 
     */
    public AgentLoginResponse createAgentLoginResponse() {
        return new AgentLoginResponse();
    }

}
