export const FETCH_APARTMENTS_REQUEST = 'FETCH_APARTMENTS_REQUEST'
export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS'
export const FETCH_APARTMENTS_ERROR = 'FETCH_APARTMENTS_ERROR'

export const CREATE_APARTMENT_REQUEST = 'CREATE_APARTMENT_REQUEST'
export const CREATE_APARTMENT_SUCCESS = 'CREATE_APARTMENT_SUCCESS'
export const CREATE_APARTMENT_ERROR = 'CREATE_APARTMENT_ERROR'

export const RESET_APARTMENTS = 'RESET_APARTMENTS'