export const FETCH_TYPES_REQUEST = 'FETCH_TYPES_REQUEST'
export const FETCH_TYPES_SUCCESS = 'FETCH_TYPES_SUCCESS'
export const FETCH_TYPES_ERROR = 'FETCH_TYPES_ERROR'

export const ADD_TYPE_REQUEST = 'ADD_TYPE_REQUEST'
export const ADD_TYPE_SUCCESS = 'ADD_TYPE_SUCCESS'
export const ADD_TYPE_ERROR = 'ADD_TYPE_ERROR'

export const DELETE_TYPE_REQUEST = 'DELETE_TYPE_REQUEST'
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS'
export const DELETE_TYPE_ERROR = 'DELETE_TYPE_ERROR'